services:
  strapi_prod:
      container_name: strapi-playground-prod
      build:
       context: ./
       dockerfile: ./Dockerfile
      # restart: unless-stopped
      env_file:
        - .env.prod
      environment:
        NODE_ENV: production
        DATABASE_CLIENT: ${DATABASE_CLIENT}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: 5432
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ports:
        - 1337:1337
      depends_on:
        - db_strapi_prod
  db_strapi_prod:
    container_name: strapi-playground-db-prod
    image: 'postgres:15.6'
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_strapi_prod:/var/lib/postgresql/data/
      #- ./database/db_strapi_latest.sql.gz:/docker-entrypoint-initdb.d/db_strapi_latest.sql.gz
    ports:
      - "5432:5432"

volumes:
  db_strapi_prod:

