###
## for referece please see https://github.com/BretFisher/nodejs-rocks-in-docker/blob/main/dockerfiles/ubuntu-copy.Dockerfile
###
###
## ubuntu base with nodejs coppied in from official image, for a more secure base
###
#cache our node version for installing later
FROM node:20-bullseye-slim AS node
FROM ubuntu:focal-20230126 AS base

# new way to get node, let's copy in the specific version we want from a docker image
# this avoids depdency package installs (python3) that the deb package requires
COPY --from=node /usr/local/include/ /usr/local/include/
COPY --from=node /usr/local/lib/ /usr/local/lib/
COPY --from=node /usr/local/bin/ /usr/local/bin/

# ensures we fix symlinks for npx, yarn and PnPm
RUN corepack disable && corepack enable

# create node user and group, then create app dir
RUN groupadd --gid 1000 node \
    && useradd --uid 1000 --gid node --shell /bin/bash --create-home node \
    && mkdir /app \
    && chown -R node:node /app

# run turbo prune to create strapi instance form monorepo and copy everything in next step
FROM base AS build
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
EXPOSE 1337
WORKDIR /app
COPY  . .

RUN pnpm install  
RUN pnpm build:dev

#run it
CMD ["pnpm", "start:dev"]
